### ISSUE TITLE
saving image to m4b removes chapter marks

### ISSUE THREAD

**Issue by ElmoFuntz** [Martchus/tageditor#45] opened 2019-03-27 02:54 UTC
M4b with chapter marks in it has them removed when using tageditor to save cover art to it. I don't know if the warning I get has anything to do with it but I get this

 - [100%] Calculating atom sizes and padding ...
 - [100%] Preparing streams ...
 - [100%] Writing header and tags ...
 - [100%] Reparsing output file ...
 - Changes have been applied.
 - Diagnostic messages:
    Warning      02:49:59   making mdhd atom: Assigned language "" is of an invalid format and will be ignored.

If I resort to adding the artwork via iTunes it works fine and chapters are retained.

**Comment by Martchus** [comment] 2019-03-27 07:21
Can you share a file to reproduce the issue?

**Comment by ElmoFuntz** [comment] 2019-03-27 12:31
The file I was doing this on is copyrighted and rather large. I will try to chop a piece off and create a small dummy/test for you later today. What is the best way to share it? I can also provide the steps I was using to create the file. I am converting audio book cd's to m4b via an ffmpeg script I wrote and inserting the chapter marks/titles also via ffmpeg then was going to use your program to insert the cover art via command line since ffmpeg has an outstanding bug where it wont insert cover art last I checked and the suggestion was to use your program as a workaround.

**Comment by Martchus** [comment] 2019-03-27 15:17
> I will try to chop a piece off and create a small dummy/test for you later today.

Sounds good.

If the M4A file is the output of ffmpeg, you can also just send me the ffmpeg command to run. The original audio source shouldn't matter much except you're using `-c:a copy`. It would also good to know the exact tageditor command you've used on that file.

**Comment by ElmoFuntz** [comment] 2019-03-27 23:44
Sure Create file:
ffmpeg -i original.mp3 -vn -y -b:a 64k -acodec aac -ac 2 temp.m4a
Inset metadata:
ffmpeg -i metadata.txt -i temp.m4a -map_metadata 1 -codec copy Book.m4b
Metadata.txt looks like this:
;FFMETADATA1
narratedBy=Nick
date=2019
year=2019-01-15
artist=Andrew
album_artist=Andrew
album=test album 
genre=Audiobook
copyright=©2018 Andrew
title=test title
author=Andrew
[CHAPTER]
TIMEBASE=1/1000
START=0
END=295354
title=Intro
[CHAPTER]
TIMEBASE=1/1000
START=295354
END=1127836
title=Recap
[CHAPTER]
TIMEBASE=1/1000
START=1127836
END=5227319
title=Chapter 1
[CHAPTER]
TIMEBASE=1/1000
START=5227319
END=7847737
title=Chapter 2
[CHAPTER]
TIMEBASE=1/1000
START=7847737
END=11114181
title=Chapter 3
[CHAPTER]
TIMEBASE=1/1000
START=11114181
END=15530570
title=Chapter 4
[CHAPTER]
TIMEBASE=1/1000
START=15530570
END=202437575
title=Chapter 5

**Comment by ElmoFuntz** [comment] 2019-03-28 00:24
Just to be sure I tried this with another audio file and a new metadata file and cover art and it still did the same thing.

**Comment by Martchus** [comment] 2019-03-28 16:59
i don't get `Warning 02:49:59 making mdhd atom: Assigned language "" is of an invalid format and will be ignored.` on an MP4/AAC file created with ffmpeg and your metadata file. And I also can not reproduce that chapters are removed. Maybe I need your exact MP4 file after all.

**Comment by ElmoFuntz** [comment] 2019-03-28 22:21
I tried it on 3 different files the 2nd one did not generate the warning but did kill the chapters. Just to be sure it wasn't size or tons of chapters I just created a small file tried again with the same results. I have attached this file with chapters. Insert any 500x500 jpg for the art.

I did notice I am getting this diagnostic message

Parsing chapters is not implemented for the container format of the file. parsing chapters
[River.zip](https://github.com/Martchus/tageditor/files/3020340/River.zip)

**Comment by Martchus** [comment] 2019-03-29 10:56
I can not reproduce the issue with your exact file. `ffprobe`, VLC and Media Info still show the characters after adding a cover using the same `tageditor` command as you. How do you test that chapters are gone? Maybe you're hitting a limitation of the player you're using?

The diagnostic message 'Parsing chapters is not implemented for the container format of the file.' is only info-level and can be ignored. It just means the chapters can not be displayed within the tag editor but of course they should still be preserved like every other aspect of the file which is unknown to the implementation.

**Comment by ElmoFuntz** [comment] 2019-03-30 21:04
I am loading it up into iTunes. Before hand there is a chapters menu and i can jump around chapters. Afterwards no menu and chapters are not displayed nor can I select them. I have not tried it on my iPhone but I expect the results to be the same.

**Comment by Martchus** [comment] 2019-03-30 21:16
I don't use iTunes. Strange that it can not display the chapters of a file processed by the tag editor while VLC, Media Info and ffprobe still can. Seems like a limitation in iTunes too me.

What happens if you remove the cover again? If iTunes shoes then the menue again we know that no information is lost when the tag editor applies changes and only iTunes can not handle such files.

Want happens if your add the cover using iTunes itself? It shouldn't produce a file it can not handle itself so we would know what the expected file structure is.

**Comment by ElmoFuntz** [comment] 2019-04-01 02:47
Removing the cover art does not make the chapters work again. Adding the cover art via iTunes works and keeps the chapters intact. I also tested on my iPhone and after adding cover art via tageditor chapters no longer work on it either. I see what you mean about ffprobe though. I do see them listed both before and after...

**Comment by Martchus** [comment] 2019-04-01 06:44
Can you share that "intact" file produced by iTunes to know what we're aiming for?

**Comment by ElmoFuntz** [comment] 2019-04-01 12:36
[River2.zip](https://github.com/Martchus/tageditor/files/3029374/River2.zip)
Ok renamed the original file I shared to River.m4b loaded it into iTunes and attached a cover image. It is attached.

**Comment by Martchus** [comment] 2019-04-15 14:39
Thanks for providing that file. Apparently the `gmhd` atom is discarded by the tag editor which is definitely a bug since the tag editor should preserve unknown parts of the file as much as possible.

I also noticed that the order of the atoms `chpl` and `mvhd` in River2.zip is different. But that's actually a change on the iTunes side.

**Comment by Martchus** [comment] 2019-04-15 16:16
Does the following file work in iTunes? [RiverTagged.zip](https://github.com/Martchus/tageditor/files/3081097/RiverTagged.zip)

If it does I have a fix :-)

**Comment by ElmoFuntz** [comment] 2019-04-16 01:58
It shows a cover but no chapters. Is there a new version I should try?

**Comment by Martchus** [comment] 2019-04-16 07:59
> It shows a cover but no chapters.

Then there's likely also some other element missing.

> Is there a new version I should try?

You would have to build the application with commit https://github.com/Martchus/tagparser/commit/2d306b1a5fd8b4960dca1810e09f37c60cf5421c yourself if you wanted to test it yourself.

**Comment by Martchus** [comment] 2019-04-16 19:58
Maybe it is the order of the elements. Does the following file work in iTunes? [RiverTagged2.zip](https://github.com/Martchus/tageditor/files/3086661/RiverTagged2.zip)

**Comment by ElmoFuntz** [comment] 2019-04-17 02:08
No same thing. Unfortunately no way for me to build or I'd try it locally.

**Comment by Martchus** [comment] 2019-04-17 10:51
Developing this is a little bit trail and error. So does the following file work in iTunes? [RiverTagged3.zip](https://github.com/Martchus/tageditor/files/3089220/RiverTagged3.zip) I've noticed that the tag editor discards a certain atom due to a bug. Maybe iTunes does not like that, too.

By the way, the bug I've found know is not limited to the iTunes and chapters. So thanks for reporting - it already helps me to improve.

> Unfortunately no way for me to build or I'd try it locally.

Likely not worth the effort anyways (unless you really want to help me coding C++).

**Comment by ElmoFuntz** [comment] 2019-04-18 02:48
No sadly still the same results.  

I "sorta" gave up on C++ I sucked at pointers sadly (and played too many games in school lol) more of a C# dabbler but very much a hobby. I do appreciate you looking at this and I'm willing to try as many versions as needed just unfortunate our time zones only permit 1 try a day usually.

**Comment by Martchus** [comment] 2019-04-18 12:23
Provides iTunes any parsing errors/warnings? And is something else broken with the file, e.g. track durations not shown or tracks completely missing? Because the only difference I still see is that the tag editor uses a newer version of the `mdhd` atom than the original file - and that part of the file contains timing information for the track. Maybe iTunes only supports version 0.

I could let the tag editor write version 0 as well for better compatibility (unless version 1 is required).

**Comment by Martchus** [comment] 2019-04-19 19:57
Seems like my tag editor sets the wrong track type for those chapter tracks. This is actually visible in MediaInfo as well. But the following file should be fixed - at least considering MediaInfo: [RiverTagged4.zip](https://github.com/Martchus/tageditor/files/3099166/RiverTagged4.zip)

Does it also work in iTunes?

**Comment by ElmoFuntz** [comment] 2019-04-20 03:02
We have a winner! That one works. Chapters and cover art show up.

**Comment by ElmoFuntz** [comment] 2019-04-26 00:25
Any eta on a release with the fix?

**Comment by Martchus** [comment] 2019-04-26 07:58
v3.2.1 which was released 2 days ago should have the fix.

**Comment by ElmoFuntz** [comment] 2019-04-26 12:47
Oops forgot to recheck ha! New version seems to do the trick. Loaded up a full chapterized book, put in the metadata and cover art and it kept the chapters and performs as expected. Thanks for all the work!

**Closed** 2019-04-26 12:55 UTC
Labels: bug
