### ISSUE TITLE
Unicode file names are not supported when writing to tag

### ISSUE THREAD

**Issue by Mapaler** [Martchus/tageditor#81] opened 2022-03-16 10:23 UTC
When the file name contains unicode characters, it cannot be written. Manually changing to the ASCII character set can be written.
![1647426112363_cmd](https://user-images.githubusercontent.com/6565860/158568934-db75a8e1-74c9-47cc-b712-ea48c7d3032a.png)

![1647426067736_tageditor](https://user-images.githubusercontent.com/6565860/158568795-5863f146-bec9-40cc-bbea-f5a896ac11c5.png)

**Comment by Martchus** [comment] 2022-03-16 10:37
What do you mean with "Manually changing to the ASCII character set"? Are you simply changing the filename to contain only ASCII-characters or are you changing the code page setting for the process?

Which version/build of Tag Editor is this and which version/build of Windows are you running it on? Which code page do you use? Is it also happening with the later Qt 5 based build? Is the CLI working when using a decent terminal¹? I'm just wondering because I've already fixed that problem at some point.

¹ Since you're using `cmd.exe`, please also be aware of https://github.com/Martchus/tageditor#windows-specific-issues.

**Comment by Martchus** [comment] 2022-03-16 10:42
Likely a regression introduced by e277070e9cc855f927ffcb0eec974a2dc8d52776.

**Comment by Mapaler** [comment] 2022-03-16 11:13
I'm using [tageditor-qt6-3.6.1-x86_64-w64-mingw32.exe.zip](https://github.com/Martchus/tageditor/releases/download/v3.6.1/tageditor-qt6-3.6.1-x86_64-w64-mingw32.exe.zip)
If I manually change the filename `あよ - 蛙楽.mp3` to `a.mp3`, the write succeeds.
![1647427703745_cmd](https://user-images.githubusercontent.com/6565860/158573358-0f204aea-5048-42a8-8008-446805dc35f1.png)
And I don't know how to changing the code page setting for the process.

The code page is automatically switched to UTF-8 after executing the *TagEditor*
![1647427869398_cmd](https://user-images.githubusercontent.com/6565860/158573908-1f8d8d17-1d76-467e-af4a-66226412cb0e.png)

The same problem exists in powershell.
![1647428823709_powershell](https://user-images.githubusercontent.com/6565860/158576558-ff325687-8b9a-4877-ad17-1f796f472949.png)

I installed v3.5.0 on [chocolatey](https://community.chocolatey.org/packages/tageditor) can successfully write to the unicode file.
![1647429154759_cmd](https://user-images.githubusercontent.com/6565860/158577458-54204536-c032-4ff1-a6c7-ae32cea4a0bb.png)

**Comment by Martchus** [comment] 2022-03-16 11:17
> And I don't know how to changing the code page setting for the process.

No problem. I suppose you've provided enough information now - especially because I could pin it down to https://github.com/Martchus/tagparser/commit/e277070e9cc855f927ffcb0eec974a2dc8d52776.

> The code page is automatically switched to UTF-8 after executing the TagEditor

Right, that's the default behavior of Tag Editor described in the linked README section I've already mentioned (https://github.com/Martchus/tageditor#windows-specific-issues).

> I installed v3.5.0 on [chocolatey](https://community.chocolatey.org/packages/tageditor) can successfully write to the unicode file.

Yes, as mentioned it is a recent regression. So I recommend to use the older version for now.

**Comment by Martchus** [comment] 2022-03-16 18:18
The problem should be fixed by: https://github.com/Martchus/tagparser/commit/4f221798e96ed50a496efa3c987826e0fd448fc3

You can try the development build: https://martchus.no-ip.biz/repo/experimental/win/tageditor-issue-81.exe

**Comment by Mapaler** [comment] 2022-03-16 19:06
The write is already successful.
![cmd_Hi2jmtt1za](https://user-images.githubusercontent.com/6565860/158664625-62f98204-490c-41f0-87ed-45af25b8e7e9.png)

<hr>
Here's another question, you see if need to open a new issue.
Open the song, do nothing, just click Save.

![tageditor-issue-81_r4OjRmuYQP](https://user-images.githubusercontent.com/6565860/158664962-4a883a1d-15bc-45b3-b00c-6808f8d064a7.png)
There is a warning that does not know what the meaning is.
![tageditor-issue-81_NLNZe8En8Y](https://user-images.githubusercontent.com/6565860/158665165-b5f82814-ea28-44b1-8c42-0e60e4b2d6da.png)
The metadata has changed. Additional ID3v1 added. It also shows that the comment tag name has changed.
![BCompare_HRzaWxyfiL](https://user-images.githubusercontent.com/6565860/158665217-275fedf8-088d-46c5-90a0-a88dab03d57b.png)

Id3v1 is also generated using the command line.
![cmd_qdPqi8HZZI](https://user-images.githubusercontent.com/6565860/158667057-f763dc51-5edc-4863-98c7-ae4c2c0d2822.png)
![BCompare_N3IEMszP1y](https://user-images.githubusercontent.com/6565860/158667221-531c1e69-d3bd-4c72-a619-e395f53cecf9.png)

Neither version can set the song title for Chinese.
![TotalCMD64_d4wNnoVvg2](https://user-images.githubusercontent.com/6565860/158667780-ff1b5a37-2f2d-4591-bdba-6b666c25b80e.png)

There is the song.
[あよ - 蛙楽.mp3.zip](https://github.com/jherby2k/AudioWorks/files/8261012/-.zip)

**Comment by Martchus** [comment] 2022-03-16 19:54
The warning is likely just that the added ID3v1 tag can not represent some of the entered values. Since the ID3v1 tag is only acting as fallback for compatibility that should be ok. Of course you can disable the creation of an ID3v1 tag in the GUI settings or via a CLI option (see README).

Note sure what the problem with the GUI's behavior is. That it takes over values from ID3v2 to ID3v1 is also expected. The comment doesn't look different except that `:XXX` is missing on the key (which shouldn't make a difference).

That the app crashes on an unhandled exception in the end is definitely a bug. However, maybe there's really an invalid multi-byte sequence specified by you.

**Comment by Mapaler** [comment] 2022-03-17 09:13
I can use the Foorbar2000 to set the ID3v1 with Chinese and Japanese.
Is TagEditor unsupportable?
![1647488129976_BCompare](https://user-images.githubusercontent.com/6565860/158775926-fa9dadcb-d785-47e0-9762-c1ff344139a7.png)

**Comment by Martchus** [comment] 2022-03-17 09:54
So far Tag Editor only uses Latin-1 in ID3v1 tags as some software has problems when putting UTF-8 there and Latin-1 seems to be the accepted default. Maybe it makes more sense to open it up for UTF-8 at this point. (It can already deal with existing UTF-8 values and if you'd use the C++ library directly you'd also be able put UTF-8 values in.)

Note that ID3v1 hasn't been invented with support for different character sets in mind. So maybe in your case it is the best to disable ID3v1 creation. I'd mention it serves as a fallback for older software not capable of reading ID3v2 tags. However, if that leads to software accidentally interpreting data in a wrong character set as you're using non-Latin-1 characters I'd say you might be better of without it after all.

**Comment by Mapaler** [comment] 2022-03-17 11:08
Thanks, I will remove ID3v1 in later work.

**Comment by Martchus** [comment] 2022-04-10 09:21
I suppose I can close this issue as the original problem has been fixed and ID3v1 is just not a good idea when using non-ASCII characters anyways.

**Closed by Martchus** 2022-04-10 09:21 UTC
Labels: bug, Windows-only
