### ISSUE TITLE
TagScanner edited mp3 takes forever to parse.

### ISSUE THREAD

**Issue by brachna** [Martchus/tageditor#6] opened 2016-11-12 14:26 UTC
Windows 8.1 x64
"tageditor-devel-2-static-x86_64-w64-mingw32.tar.xz"

mp3 files edited using TagScanner software don't load, they show "The file is beeing parsed..." and it keeps going forever.

**Comment by Martchus** [comment] 2016-11-12 15:37
Could you provide a sample file?

Thanks for all the feedback so far.

**Comment by brachna** [comment] 2016-11-12 16:11
Here's an example. You're welcome.
[01 - Can We Lie Here-.zip](https://github.com/Martchus/tageditor/files/587309/01.-.Can.We.Lie.Here-.zip)

**Comment by Martchus** [comment] 2016-11-12 18:32
I can reproduce and will check what's going on. Even if the file is not 100% valid, the Tag Editor should be able to handle it.

**Comment by Martchus** [comment] 2016-11-13 12:13
The file is valid. The problem is that use of `std::stringstream<char16_t>` throws `std::bad_cast`. I'll have to work around this.

**Comment by Martchus** [comment] 2016-11-13 21:49
Should be fixed. I haven't committed the changes yet because I have to check whether it didn't break anything else.
Here's another build which includes the fix: http://martchus.no-ip.biz/repo/win/static/tageditor-devel-4-static-x86_64-w64-mingw32.tar.xz

**Comment by brachna** [comment] 2016-11-14 01:25
I confirm that the issue is fixed with provided latest build.

**Comment by Martchus** [comment] 2016-11-18 17:01
Then I close this :-)
Thanks for the feedback.

**Closed by Martchus** 2016-11-18 17:01 UTC
Labels: bug
