### ISSUE TITLE
adding cover art to opus produces corrupted file on occasion

### ISSUE THREAD

**Issue by blueclouds8666** [Martchus/tageditor#70] opened 2021-08-15 01:37 UTC
i have found that, when using very certain .png files as the cover art for opus, it will produce a likely corrupted/non-standard file. despite the resulting file being playable with most audio players, it causes some unexpected behavior:

- dBpoweramp reports the file as "Unable to read track details, file corrupted or not supported"
- K-Lite codecs are unable to load the cover art (for the explorer thumbnail) despite being embedded into the file
- ffprobe reports with a warning "3 bytes of comment header remain"

these issues don't happen with the vast majority of files generated by Tag Editor; only those rare instances.
to be sure, i tested the PNG file with a tool called [pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) and it is reported as valid. ffprobe also shows the original opus file to be correct. since this isn't very usual to happen, [here](https://mega.nz/file/LbRE2ZqJ#pAlznMY1HjtlS8lhztnZrP8IRCKwUSOwipL77H39GQs) is a sample. used command is the following:

`tageditor -s cover=cover.png -f audio.opus`

sample includes an audio track, as it seems that could also be a factor (applying cover.png to almost any opus file will corrupt it, but with certain opus files there will be no corruption for some reason. perhaps it has something to do with byte alignment)
both 3.4.2 and the latest development build have the same issue, both with the GUI and command line.

**Comment by Martchus** [comment] 2021-08-15 10:53
I'll check it out later. Thanks for reporting.

**Comment by Martchus** [comment] 2021-08-16 10:01
I've been investigating this yesterday but haven't been able to implement a fix yet. Just for the record, the problem is that the size of the tag is a multiple of 255 in which case one needed to add a trailing zero lacing value. Otherwise tools like ffmpeg think the next packet (in this case 3 bytes long) belongs the the one containing the tag.

**Comment by Martchus** [comment] 2021-08-16 17:31
It should be fixed on master, I'll create a development build for Windows. The new version will also be able to show a warning when encountering such a file like ffmpeg does.

**Comment by Martchus** [comment] 2021-08-16 21:33
Development build for Windows: http://martchus.no-ip.biz/repo/arch/ownstuff-experimental/os/x86_64/mingw-w64-tageditor-qt6-3.4.3-1-any.pkg.tar.zst

**Comment by blueclouds8666** [comment] 2021-08-17 13:54
tested it, works well and the issues with K-Lite and dBpoweramp no longer happen.

**Comment by Martchus** [comment] 2021-08-18 20:52
The new release has the fix so I'm closing the issue.

**Closed by Martchus** 2021-08-18 20:52 UTC
Labels: bug
