### ISSUE TITLE
Corrupted Files - Bak Files?

### ISSUE THREAD

**Issue by action1618** [Martchus/tageditor#85] opened 2022-07-09 12:49 UTC
Hello, I really enjoy and appreciate this software but I am noticing 1/10 files are typically becoming corrupted and will not playback.

It appears files that would not be parsed correctly offer a warning that this will happen. I notice the Bak files are automatically generated and must be are likely created as the JUST INCASE. Could you explain how I can use the bak files through the software to undo corrupted files? 

Thanks,

**Comment by Martchus** [comment] 2022-07-09 14:23
> but I am noticing 1/10 files are typically becoming corrupted

In order to improve that I need an example file or at least further details about the file. The file's format and internal structure might be different/special and the underlying library cannot handle it. Maybe it is easy to fix but not without an example file and you telling me what you've did and what settings you've used.

> It appears files that would not be parsed correctly offer a warning that this will happen.

What warning? It would be very useful to state it because there can be many different warnings.

> I notice the Bak files are automatically generated and must be are likely created as the JUST INCASE.

Please see https://github.com/Martchus/tageditor#backuptemporary-files=. So these files are generated for technical reasons but *also* serve as a backup.

> Could you explain how I can use the bak files through the software to undo corrupted files?

Just delete the broken file and rename the `.bak` file back to its original name (basically dropping the `.bak` extension). You can use any program for that. The tag editor itself doesn't allow renaming files.

---

By the way, what platform are you using and what version of Tag Editor and the underlying tagparser and c++utilities libraries? If you're using older versions, please try again with the latest versions.

**Comment by notjustanygeek** [comment] 2022-07-13 18:39
Hey I have had the same issue.

I notice that some files will end up truncated, while most of them will work fine. For example I have a video file, a 4K video downloaded from a primary source on the internet via a subscription. I have had this similar result occur for other file types, regardless of file size, resolution, etc.

Here is the diagnostic info that you may need:

Settings:

- add mp4/itunes tag

Structure:

![image](https://user-images.githubusercontent.com/8071625/178806015-97006ac3-ce38-4f3c-b8c3-106c0c7f7588.png)

Tracks:
![image](https://user-images.githubusercontent.com/8071625/178806244-eac4fd1a-0f2b-4d54-8469-e974d35c11d7.png)

Other Data
![image](https://user-images.githubusercontent.com/8071625/178806374-56b43f1e-fb94-41f1-bd8b-6a2e0963c109.png)

Messages after attempting to edit tags:

![image](https://user-images.githubusercontent.com/8071625/178806595-9f7a7fb2-be4f-45b0-9e43-c33d9fd6a448.png)

File information following attempt to edit tags:

![image](https://user-images.githubusercontent.com/8071625/178806757-281998ad-c814-4986-a2ef-e9125e298bdc.png)

![image](https://user-images.githubusercontent.com/8071625/178806856-a5fabbe5-acb2-4a8b-a9b4-d9509caac38d.png)

**Comment by notjustanygeek** [comment] 2022-07-13 18:40
I hope you can fix this issue and release an update, I really like this utility, its a great help.

**Comment by Martchus** [comment] 2022-07-13 21:54
I could reproduce the problem with the i686 version (using the i686 Windows build via WINE). The x86_64 builds work just fine (tested GNU/Linux and Windows builds) so I recommend to simply use those builds for now. Your system will most likely support it and you might even get better performance.

I still try to fix the issue for the i686 build, though.

**Comment by Martchus** [comment] 2022-07-13 23:16
The i686 build should be fixed by https://github.com/Martchus/cpp-utilities/commit/fe6ad813409b42b2e303e35f02e036497cc81141. At least with my test file it works now.

I've been replacing the binaries of the latest release found in the GitHub release section. Not the best practice but less effort for me and supposedly other packagers.

@action1618 Not sure whether this also fixes the issue you have initially reported. If that issue is not fixed, please provide more information as mentioned in my previous comment.

**Comment by notjustanygeek** [comment] 2022-07-14 21:26
Wow amazing, that was so fast, thank you very much.

I don't know how I did it, but I think I accidentally removed all the tags associated with the files in that directory, because now I have to manually select mp4 tag each time, oops.

I guess I was using the 32 bit version but, and maybe its just me, I didnt realize because all of the versions had "64" somewhere written in the file name, and I really thought I was using the 64 bit version. I went and downloaded the one you specified and it worked immediately; I didnt try it with the version you mentioned, but I'm glad you are so thorough that you tried all these things before handing off back to my side. I really appreciate your efforts! Thanks for this great tool. I wonder what other cool things I can use it for.

Thanks!

**Comment by Martchus** [comment] 2022-07-14 21:56
> Wow amazing, that was so fast, thank you very much.

Glad to help.

> because now I have to manually select mp4 tag each time, oops.

If you enable automatic tag management in the (in the "Tag management" menu) it should create the tag automatically for you.

> I didnt realize because all of the versions had "64" somewhere written in the file name

Both also have 32 somewhere written in the file name as the filename includes the full "GNU triplet" of the platform the binary has been compiled for. The documentation explains the format if you're curious: https://www.gnu.org/software/autoconf/manual/autoconf-2.70/html_node/Specifying-Target-Triplets.html

> I really appreciate your efforts! Thanks for this great tool.

Thanks for the kind words :-)

**Comment by Martchus** [comment] 2022-07-14 21:58
I'm also closing the issue now as it is most likely done.

@action1618 Feel free to re-open if that's not the case for the issue you've initially reported.

**Closed by Martchus** 2022-07-14 21:58 UTC
Labels: bug, question
