### ISSUE TITLE
TagScanner recognizes FLAC with embedded cover (in Tag Editor) as corrupted data.

### ISSUE THREAD

**Issue by brachna** [Martchus/tageditor#7] opened 2016-11-13 01:45 UTC
Windows 8.1 x64
"tageditor-devel-3-static-x86_64-w64-mingw32.tar.xz"

Cover art embedded in MP3 using Tag Editor isn't recognized in Clementine. TagScanner recognizes it just fine though.

Cover art embedded in FLAC using Tag Editor isn't recognized in Clementine. TagScanner says "Corrupted data or unknown format".

When embedded using TagScanner the cover shows up in Clementine.

**Comment by brachna** [comment] 2016-11-13 02:24
Actually now it does...
Very confusing, it might actually be a problem on Clementine part, not Tag Editor.

**Comment by brachna** [comment] 2016-11-13 04:22
Tomahawk player doesn't show cover of files saved with Tag Editor, but TagScanner ones it shows.
Might be a problem of Tomahawk problem though.

**Comment by Martchus** [comment] 2016-11-13 12:05
Not sure but I'll can check (have tested the FLAC processing a little bit less anyways).

**Comment by Martchus** [comment] 2016-11-18 17:00
> Actually now it does...

Maybe it was showing cached tags/cover before and at the time the cache entry was created the cover hasn't been added yet.

> TagScanner still says "Corrupted data or unknown format" in FLAC case.

Since this bug can only be reproduced with proprietary, Windows-only software I will not put any effort in it. However, if you can provide a sample file and point out how it is corrupted by Tag Editor I will fix the issue of course.

> Tomahawk player doesn't show cover of files saved with Tag Editor

I don't use Tomahawk, but other taglib-based player like Amarok show cover saved with Tag Editor.

**Comment by brachna** [comment] 2016-11-19 05:04
>Since this bug can only be reproduced with proprietary, Windows-only software I will not put any effort in it. However, if you can provide a sample file and point out how it is corrupted by Tag Editor I will fix the issue of course.

[Sky Flying By - Detour- One Year Later - 02 No Where Near.zip](https://github.com/Martchus/tageditor/files/601264/Sky.Flying.By.-.Detour-.One.Year.Later.-.02.No.Where.Near.zip)
Steps to create such file were:
1. took file with a cover;
2. removed cover in Tag Editor;
3. saved (this is the file I uploaded);
4. TagScanner says it's either unknown or corrupted data (says about the cover data, not about the file in general).
It's probably a fault of TagScanner.

Shame about Tomahawk, but it might be its own problem anyway: https://github.com/tomahawk-player/tomahawk/issues/548

**Comment by Martchus** [comment] 2016-11-19 13:52
Thanks for providing the sample file.

There was actually a bug in the tagparser library which lead to empty `METADATA_PICTURE_BLOCK` when removing a cover. This is fixed in latest commits.

Here a new build containing latest fixes: https://martchus.no-ip.biz/repo/win/static/tageditor-devel-6-static-x86_64-w64-mingw32.tar.xz

Not sure about Tomahawk. But cover in FLAC files is not too common so I wouldn't expect support for it everywhere.

**Comment by brachna** [comment] 2016-11-19 18:18
I confirm that the issue is fixed with latest provided build. Thank you.

**Closed** 2016-11-19 18:18 UTC
Labels: bug
