### ISSUE TITLE
resulting file is corrupted for large audio files

### ISSUE THREAD

**Issue by blueclouds8666** [Martchus/tageditor#69] opened 2021-08-12 22:07 UTC
I have an opus audio file (.opus) with a total size of 500 MB. When trying to add metadata to the file, the resulting file is way smaller in size, around 40 MB, and the audio track seems corrupted as audio segments are missing.

As an example, i've used [this](https://mega.nz/file/XGJDlYKS#VqcoeYtlLE_yP7lyVSmRi_ouBdU9fAVT-rg_3WFO6Ek) file with the following command for adding a cover:

`tageditor -s cover=cover.png -f audio.opus`

I'm using the latest release available (3.4.2) under Windows. Adding the cover from the GUI results in the same. I'm unsure if the same issue is present with other formats beside the ogg container.

**Comment by Martchus** [comment] 2021-08-12 22:11
I've only tested with smaller opus/ogg so far. Thanks for providing a sample file. I'll have a look tomorrow.

**Comment by Martchus** [comment] 2021-08-13 16:36
I can reproduce the problem. I hope I can fix it soon. The reason is possible the menu stream within that file.

**Comment by Martchus** [comment] 2021-08-13 17:19
Oh, this is because the parser omits pages in the middle of a big file to speed up the process. Unfortunately I didn't take into account that this affects applying changes as well. When using the GUI and forcing a full parse the problem shouldn't happen. I'll create a fix.

**Comment by Martchus** [comment] 2021-08-13 19:07
Should be fixed within the tagparser project. If you'd like test it I can provide a development build later or tomorrow.

**Comment by blueclouds8666** [comment] 2021-08-13 19:21
> Should be fixed within the tagparser project. If you'd like test it I can provide a development build later or tomorrow.

Yes that would be great

**Comment by Martchus** [comment] 2021-08-14 10:31
A development build for Windows can be found here: https://martchus.no-ip.biz/repo/arch/ownstuff-experimental/os/x86_64/mingw-w64-tageditor-qt6-3.4.2-1-any.pkg.tar.zst
I've only tested it under GNU/LInux so far but it shouldn't make a difference.

**Comment by blueclouds8666** [comment] 2021-08-15 01:37
tried a few large opus files with the development build and everything seems to work fine now, as well as the windows build.

**Comment by Martchus** [comment] 2021-08-18 20:52
The new release has the fix so I'm closing the issue. Btw, the soundtrack is quite nice and actually kind of special. Reminds me of the good old times  playing the game :-)

**Closed by Martchus** 2021-08-18 20:52 UTC
Labels: bug
