### ISSUE TITLE
Truncated output when writing non-ASCII characters

### ISSUE THREAD

**Issue by ghost** [Martchus/tageditor#15] opened 2016-12-09 00:39 UTC
With this file (regionsAllowed=DE,US):

~~~
youtube-dl --add-metadata --format m4a 2Y6Nne8RvaA
~~~

I am getting this output with TagEditor master:

~~~
$ tageditor -gf 'Kungs vs Cookin’ on 3 Burners - This Girl-2Y6Nne8RvaA.m4a'
Tag information for "Kungs vs Cookin� on 3 Burners - This Girl-2Y6Nne8RvaA.m4a":
MP4/iTunes tag
 Title             Kungs vs Cookin’ on 3 Burners - This Gir
~~~

Notice that output is truncated, also notice that TagEditor chokes on the 1st
typographic quote, but not the 2nd. Proper FFprobe output:

~~~
$ ffprobe 'Kungs vs Cookin’ on 3 Burners - This Girl-2Y6Nne8RvaA.m4a'
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from
'Kungs vs Cookin’ on 3 Burners - This Girl-2Y6Nne8RvaA.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 512
    compatible_brands: isomiso2
    title           : Kungs vs Cookin’ on 3 Burners - This Girl
    artist          : Kungs Listen ad-free with YouTube Red
    date            : 20160324
    encoder         : Lavf57.58.101
    comment         : Kungs vs Cookin’ on 3 Burners - This Girl.
~~~

**Comment by Martchus** [comment] 2016-12-09 07:45
Works under GNU/Linux. Please note limitations [regarding text encoding](https://github.com/Martchus/tageditor#text-encoding--unicode-support) - especially under Windows. So currently input parameters must be UTF-8 and output will always be UTF-8, too. Not sure what your terminal provides and why it is truncated.

I'm trying to fix those encoding issues but it might be difficult and will take some time. In my opinion it would be best to just use [UTF-8 everywhere](http://utf8everywhere.org/).

BTW: ffmpeg output is also truncated because comment has multiple lines.

**Comment by svnpenn** [comment] 2016-12-09 12:15
@Martchus the actual FFprobe output is correct, I just shortened it to show
enough that it goes past TagEditor and it prints non ASCII correctly. If it
helps I did extensive work on this issue in the JQ project, I will link those
issues.

**Comment by svnpenn** [comment] 2016-12-09 12:43
https://github.com/Martchus/tageditor/issues/4

**Comment by Martchus** [comment] 2016-12-10 14:59
So I would have to do the same as in https://github.com/stedolan/jq/commit/7811ef1e1746f0963deb960af2c9623fb53c24a5 and https://github.com/stedolan/jq/pull/824/commits/97a2f34cc9ee9e4b08b7171b955879f6afef39e3. I would also have to use  `__gnu_cxx::stdio_filebuf b (_wopen (L"filename", _O_RDONLY));` instead of `std::fstream` under Windows then. Seems messy and like a lot of work. Not sure whether it is worth it.

It seems like your knowledge about Windows and its way of handling non-ASCII characters is much better then mine so if you have time and interest you might fix this issue yourself.

In the meantime you can just use a terminal emulator that supports UTF-8.

**Comment by Martchus** [comment] 2016-12-15 22:02
Looked a little bit into it and it seems to be less work than expected - so I'm working on it.

**Comment by svnpenn** [comment] 2016-12-15 22:12
@Martchus thanks. I got sidetracked on writing an MTA in Awk:

http://github.com/svnpenn/a/blob/4a29efa/etc/mailing-list.sh

**Comment by Martchus** [comment] 2016-12-18 19:24
Created `fix/windows_unicode` branch on c++utilities, tagparser and tageditor but it doesn't work yet. Currently there is no further output after printing a string containing UTF-8 characters. Not sure what's wrong.

**Comment by Martchus** [comment] 2016-12-18 19:48
When testing under Windows (previously I tested with Wine) the output is no longer truncated and the terminal states the codepage is UTF-8 (under properties / options). The special characters are still messed, though.

When testing with MSYS2 terminal, everything works as expected.

If it also works for you now, let me know and I'll merge the changes. I also attached the build I tested with.

[tageditor.zip](https://github.com/Martchus/tageditor/files/659614/tageditor.zip)

**Comment by svnpenn** [comment] 2016-12-18 20:31
@Martchus I guess this is better? It is printing the typographic quote, but no
tags?

~~~
$ tageditor -gf 'Kungs vs Cookin’ on 3 Burners - This Girl-2Y6Nne8RvaA.m4a'
Kungs vs Cookin’ on 3 Burners - This Girl-2Y6Nne8RvaA.m4
~~~

**Comment by Martchus** [comment] 2016-12-18 20:38
Then you have the same problem as me when I tested under Wine (except that I've got the a of .m4a at the end). Not sure why this happens.

**Comment by svnpenn** [comment] 2016-12-18 20:40
From a clean Windows install, you need to `chcp 65001`, as detailed in the linked threads. Not sure if you were already doing that

**Comment by Martchus** [comment] 2016-12-18 21:27
* No, but with commit https://github.com/Martchus/cpp-utilities/commit/88b82e095546cd45c225b9bc1880a58db818ea7f the code page is set for the terminal IO which should actually work because the tageditor always writes UTF-8 to stdout (regardless of the character set use within the tag).
* And this should convert the command line args from UTF-16 to UTF-8: https://github.com/Martchus/cpp-utilities/commit/6f5cc349c5245c34153e443ae41cac8d1df40dcb
* I'm also using _wopen to support unicode filenames now: https://github.com/Martchus/tagparser/commit/42b97f281fe84d7e7a3df474f7215fb71e3bc1b3

All of these commits are included in the build I've attached in previous comment.

**Comment by svnpenn** [comment] 2016-12-18 22:45
@Martchus Here is a simple test to display the issue:

~~~
youtube-dl --format m4a --fixup never --output alfa.m4a 2Y6Nne8RvaA
ffmpeg -i alfa.m4a -c copy -metadata date=20160324 -metadata title=z bravo.m4a
ffmpeg -i alfa.m4a -c copy -metadata date=20160324 -metadata title=Ω charlie.m4a
~~~

Instead of adding full metadata, we are only adding 2 tags to narrow the issue.
Here is FFprobe output:

~~~
$ ffprobe bravo.m4a
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'bravo.m4a':
  Metadata:
    title           : z
    date            : 20160324
~~~

~~~
$ ffprobe charlie.m4a
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'charlie.m4a':
  Metadata:
    title           : Ω
    date            : 20160324
~~~

TagEditor with normal text:

~~~
$ tageditor -gf bravo.m4a
bravo.m4a
Tag information for "bravo.m4a":
MP4/iTunes tag
 Title             z
 Year              20160324
 Encoder           Lavf57.58.101
~~~

TagEditor with problem text:

~~~
$ tageditor -gf charlie.m4a
charlie.m4a
Tag information for "charlie.m4a":
MP4/iTunes tag
 Title             Ω
~~~

Notice it does print the character in question, but stops and does not print the
Year tag.

**Comment by svnpenn** [comment] 2016-12-18 22:51
![untitled](https://cloud.githubusercontent.com/assets/926619/21297273/4459c912-c542-11e6-9d5f-580d23cd18c6.png)

**Comment by svnpenn** [comment] 2016-12-18 22:52
![untitled](https://cloud.githubusercontent.com/assets/926619/21297285/5e08045a-c542-11e6-9f00-d1a91091e366.png)

**Comment by Martchus** [comment] 2016-12-19 23:19
Can't reproduce with latest binary. I've just opened cmd.exe and the following works:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Martchus>D:

D:\>cd tmp

D:\tmp>tageditor -gf bravo.m4a

D:\tmp>bravo.m4a
Tag information for "bravo.m4a":
MP4/iTunes tag
 Title             z
 Year              20160324
 Encoder           Lavf57.56.100


D:\tmp>tageditor -gf charlie.m4a

D:\tmp>charlie.m4a
Tag information for "charlie.m4a":
MP4/iTunes tag
 Title             Ω
 Year              20160324
 Encoder           Lavf57.56.100

````

Also UTF-8 in filename works now:

```
D:\tmp>Glóandi.mp3
Tag information for "Glóandi.mp3":
ID3v1 tag
 Title             test
 Genre             Blues

```

However, setting tags with UTF-8 characters doesn't work yet.

Just to ensure I didn't upload an old build last time, here the executable I've just tested with: [tageditor.zip](https://github.com/Martchus/tageditor/files/662398/tageditor.zip)

**Comment by svnpenn** [comment] 2016-12-20 00:32
@Martchus keep in mind while I am using Windows in actuality, for the purposes
of this issue I am running the tests in a pristine Windows virtual machine with
Virtualbox:

    en_windows_7_ultimate_with_sp1_x64_dvd_u_677332.iso

Here is FFprobe result:

~~~
C:\>ffprobe charlie.m4a
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'charlie.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 512
    compatible_brands: isomiso2
    title           : Ω
    date            : 20160324
~~~

Here is TagEditor:

~~~
C:\>tageditor -gf charlie.m4a

C:\>charlie.m4a
Tag information for "charlie.m4a":
MP4/iTunes tag
 Title             Ω
~~~

Some things are wrong here.

1. Unlike FFprobe, TagEditor actually return before it is even finished
   printing. You can see this even with your own example, which is why you have
   two `D:\tmp>` in your example and I have two `C:\>` in mine

2. Output stops before printing all tags

3. Normally you can redirect output with `> file`, however TagEditor ignores
   such redirection and still goes straight to STDOUT

**Comment by svnpenn** [comment] 2016-12-20 00:34
Note I am using Windows 7

~~~
Microsoft Windows [Version 6.1.7601]
~~~

**Comment by Martchus** [comment] 2016-12-27 23:38
The pipe/redirect issues and other weird behaviour might be caused by setting the code page to UTF-8 (which seems to be no very well supported). However, when not setting the code page to UTF-8, not all characters will be displayed correctly. So I currently see no way to print Unicode characters except using UTF-16 which is not what I want.

The tag editor should work well using Mintty, though. So I propose to simply use Mintty or any other terminal emulator which can handle UTF-8. I only tested Mintty provided by MSYS2, but the Cygwin version should work, too.

BTW: Other Unicode issues reported in https://github.com/Martchus/tageditor/issues/4 should be fixed now.

**Comment by svnpenn** [comment] 2016-12-28 00:00
Um, this is not a good solution? FFprobe is working as expected, in the same environment. We just give up because it is too hard? I can try a patch if needed

**Comment by Martchus** [comment] 2016-12-28 00:14
I didn't say I give up (or even close the issue).

Currently I just don't see a feasible solution and since I don't use Windows often (and if MSYS2 terminal) this is not on top of my priority list.

But I would appreciate your help on this of course.

**Comment by Martchus** [comment] 2016-12-28 17:36
> FFprobe is working as expected

Not sure whether FFprobe has actual Unicode support under Windows. Maybe it just converts the output to match the current code page. This might work for some non-ASCII characters but not for all Unicode characters.

BTW: If you provide a patch, it must ensure that UTF-8 output is still possible because that is my main use case (and likely the use case of any GNU/Linux user): full Unicode support under any terminal supporting UTF-8

**Comment by svnpenn** [comment] 2016-12-28 18:47
If I do a patch it will be UTF-8. Also note that JQ works fine on Windows too, as previously discussed

**Comment by Martchus** [comment] 2016-12-29 00:04
Great 👍

**Comment by svnpenn** [comment] 2018-02-19 00:31
https://github.com/Martchus/tageditor/issues/35

**Comment by svnpenn** [comment] 2018-02-22 01:50
@Martchus note that in addition to FFmpeg, at least 2 other projects support
non-ASCII characters with Windows:

~~~
youtube-dl --add-metadata --format m4a --output z.m4a 2Y6Nne8RvaA
~~~

~~~
$ mp4box -info z.m4a
Name: Kungs vs Cookin’ on 3 Burners - This Girl
Artist: Kungs, Cookin' On 3 Burners
Comment: Kungs vs Cookin’ on 3 Burners - This Girl.
Created: 20160324
Encoder Software: Lavf58.9.100
~~~

http://github.com/gpac/gpac

~~~
$ mp4tag z.m4a
Name:[S] Kungs vs Cookin’ on 3 Burners - This Girl
Artist:[S] Kungs, Cookin' On 3 Burners
Comment:[S] Kungs vs Cookin’ on 3 Burners - This Girl.
Date:[S] 20160324
Tool:[S] Lavf58.9.100
~~~

http://github.com/axiomatic-systems/Bento4

**Comment by Martchus** [comment] 2018-02-22 02:13
@svnpenn Note that gpac and Bento4 use `printf` and similar C functions for the console output like ffmpeg. So all of those applications do basically the same for writing to the console. There is no use in listing further applications of that kind.

This is because the tag editor uses standard C++ streams provided by `libstdc++` rather then `printf`. This is obviously buggy under the default Windows terminal when using UTF-8. It would be more helpful to find further projects which use streams as well because those projects might actually contain workarounds which could be applied to the tag editor.

And not, switching to C-style standard I/O is not an option for the tag editor. There would be too much to change for almost no benefit.

In fact, I believe the cleanest solution would be fixing this in `libstdc++` itself. Or even in the terminal itself in case `libstdc++` is actually doing fine and also just running into a bug caused by the terminal.

**Comment by cup** [comment] 2018-12-09 20:42
@Martchus have you seen this?

http://github.com/fmtlib/fmt

**Comment by cup** [comment] 2018-12-09 20:48
@Martchus have you seen these?

- http://fmtlib.net
- http://github.com/facebook/folly/blob/master/folly/docs/Format.md

**Comment by Martchus** [comment] 2018-12-09 22:46
I'm in fact aware of that library and would consider it when creating a new project. Rewriting the tag editor's CLI output would be doable, too. However, I'm currently not motivated to take that effort. Sounds like a tedious task.

**Comment by nu8** [comment] 2020-10-18 01:16
I believe this issue can be closed. It appears the issue is specific to older
Windows versions. If you wish to support those fine, but it will be painful.
Starting with Windows 10 1903 (May 2019), you can use Windows Terminal:

https://github.com/Microsoft/Terminal

To test, I installed this into a pristine virtual machine. I then turned on
Unicode:

~~~
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
"OEMCP"="65001"
~~~

and restart. Running this command:

~~~
youtubedr -d . -i 140 -o a.m4a 2Y6Nne8RvaA
ffmpeg -i a.m4a -c copy -metadata date=20201017 -metadata title=😀 b.m4a
tageditor -gf b.m4a
~~~

https://github.com/kkdai/youtube

works as expected all the way back to TagEditor 2.1.0 (Nov 2016). However I will
say that one previously mentioned issue remains. TagEditor is not waiting for
the command to complete. It exits immediately, which produces console artifacts
as previously discussed in the thread. @Martchus, should I open a new issue?

**Comment by Martchus** [comment] 2020-10-18 10:52
> TagEditor is not waiting for
> the command to complete. It exits immediately, which produces console artifacts
> as previously discussed in the thread.

Likely the problematic code is within this function: https://github.com/Martchus/cpp-utilities/blob/master/application/commandlineutils.cpp#L89

This code tries to solve the following problem: The tag editor has a GUI and a CLI. Both are (due to historical reasons) part of the same executable. That works fine under Linux. However, I've noticed that I don't get any console output under Windows without taking extra care (which the mentioned function is supposed to do). There's definitely room for improvement but I was never willing to spend the extra effort because I only use the GUI under Windows (and maybe in rare cases the CLI with MSYS2).

> @Martchus, should I open a new issue?

I don't care. I guess we can just keep using this issue.

**Comment by Martchus** [comment] 2021-05-28 17:30
With https://github.com/Martchus/cpp-utilities/commit/1ac1104535cd5da1493a3c0642747b19f0e87163 non-ASCII characters are displayed correctly within `cmd.exe` of a recent Windows system. Without it one can still set the console's character set manually to UTF-8.

There are still problems when using the default console under Windows which I'm tracking within https://github.com/Martchus/tageditor/issues/41. So I'm closing this one.

**Closed by Martchus** 2021-05-28 17:30 UTC
Labels: Windows-only, bug
