### ISSUE TITLE
 File names with non ASCII characters

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#21] opened 2017-08-17 02:32 UTC
With this file (regionsAllowed=DE,US):

~~~
youtube-dl --add-metadata --format m4a --output Ω.m4a wMeyeS_7YXU
~~~

I am getting this output with TagEditor master:

~~~
$ tageditor -gf Ω.m4a
Error: An IO failure occured when reading the file "��.m4a".
~~~

Proper FFprobe output:

~~~
$ ffprobe Ω.m4a
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Ω.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 512
    compatible_brands: isomiso2
    title           : Aphex Twin - Stone In Focus
    artist          : Diego Acosta
    date            : 20160503
    encoder         : Lavf57.76.100      
~~~

**Comment by svnpenn** [comment] 2017-08-17 02:34
https://github.com/stedolan/jq/issues/811

**Comment by svnpenn** [comment] 2017-08-17 02:35
https://github.com/Martchus/tageditor/issues/4

**Comment by Martchus** [comment] 2017-08-17 12:32
Did you compile c++utilities with USE_NATIVE_FILE_BUFFER so https://github.com/Martchus/cpp-utilities/blob/master/io/nativefilestream.cpp#L33 is executed?

Did it work for you before (regression?) and does the GUI work? I assume you still use the crappy standard terminal?

From the error message I would say, the file name has been at least internally converted to UTF-8, although the terminal doesn't handle it too well. Then, in theory, the "native file buffer" approach should be able to handle it correctly by converting it back to UTF-16 and passing it to a special MS fopen function.

**Comment by Martchus** [comment] 2017-08-20 14:10
I've just tested it using `cmd.exe` from Windows 10:

```
D:\tmp>tageditor.exe -g -n title -f Ω.m4a

D:\tmp>╬®.m4a
Tag information for "╬®.m4a":
MP4/iTunes tag
 Title             Highway To Hell


D:\tmp>
```

So it works. Messed/truncated output of non-ASCII characters is [another issue](https://github.com/Martchus/tageditor/issues/15) which can easily be worked around using a decent terminal like mintty (standard terminal which comes with MSYS2). The GUI works as well.

So I assume you didn't compile with `USE_NATIVE_FILE_BUFFER`. The only other explanation I can think of is that the define `CPP_UTILITIES_USE_NATIVE_FILE_BUFFER` is not propagated correctly in the build system and hence to present anymore when building the tagparser library.

**Comment by svnpenn** [comment] 2017-08-20 14:45
> Did you compile c++utilities with USE_NATIVE_FILE_BUFFER so

Initially no, but upon trying it now the error persists.

> Did it work for you before (regression?)

Yes, the behavior has changed since this issue:

http://github.com/Martchus/tageditor/issues/15

> I assume you still use the crappy standard terminal?

Yes, it is important to do so. As I have shown above, if FFmpeg/JQ can handle
it correctly, then TagEditor should be able to as well.

> From the error message I would say, the file name has been at least internally
> converted to UTF-8, although the terminal doesn't handle it too well.

Its not the terminal that is the problem, it is the code. If you check the
previous JQ issue, you can see same problem was discussed at length and resolved
2 years ago:

http://github.com/stedolan/jq/issues/811

> So it works. Messed/truncated output of non-ASCII characters is another issue
> which can easily be worked around using a decent terminal like mintty
> (standard terminal which comes with MSYS2).

Saying, "use a better terminal" is really a roundabout way of saying, "I dont
know how or dont care to fix the problem". This problem has been encountered and
fixed with the FFmpeg project and the JQ project, so it is a fixable problem.

**Comment by svnpenn** [comment] 2017-08-20 14:54
> I've just tested it using cmd.exe from Windows 10:

Also, Windows 10 uses ConHost V2, so if you are interested in supporting
Windows 7, you need to be testing with the Window 7 console:

http://cygwin.com/ml/cygwin/2017-07/msg00442.html

**Comment by Martchus** [comment] 2017-08-20 15:33
Ok, so it is a regression. Then I still suspect that the define CPP_UTILITIES_USE_NATIVE_FILE_BUFFER is not propagated correctly in the build system and hence to present anymore when building the tagparser library. So the important question remains: Is https://github.com/Martchus/cpp-utilities/blob/master/io/nativefilestream.cpp#L33 is executed?

> Its not the terminal that is the problem, it is the code

That is true, hence the workaround enabled via `USE_NATIVE_FILE_BUFFER`.

---

Saying, "use a better terminal" is
* providing a workaround
* saying the issue is indeed not very important
* *not* saying that the problem can not be fixed

I'm not interested in testing various versions of Windows (or different Linux distributions, ...) for the simple reason that I don't have the time to do so.

> Yes, it is important to do so.

Just out of interest, why would this be the case? You think that FFmpeg/JQ put effort into it makes it important?

> As I have shown above, if FFmpeg/JQ can handle it correctly, then TagEditor should be able to as well.

Note that these projects are not provided by a single developer. Hence they can put much more effort into fixing Windows-specific bugs. Maybe even some of the developers of these projects use Windows and hence have it higher on their priority list. So you can not compare these projects with this Tag Editor.

**Comment by svnpenn** [comment] 2017-08-20 15:36
Windows 7 is the most used operating system in the world:

http://netmarketshare.com/operating-system-market-share.aspx

do you really want to say that you do not support it?

**Comment by svnpenn** [comment] 2017-08-20 17:32
@Martchus I did some more testing and this looks to be a problem with TagEditor
specifically. Using this combination:

- TagEditor: v2.1.0
- TagParser: master
- CPP-Utilities: master

I was able to revert the error in my original post. However starting with
TagEditor v2.1.1, the error crops up. Also I noticed that the character has an
effect. Using this file:

~~~
youtube-dl --add-metadata --format m4a --output alfa.m4a wMeyeS_7YXU
~~~

If the character is on [Windows 1252][1], all is well:

~~~
$ cp alfa.m4a €.m4a
$ tageditor/tageditor -gf €.m4a
Tag information for "�.m4a":
MP4/iTunes tag
 Title             Aphex Twin - Stone In Focus
 Artist            Diego Acosta
 Year              20160503
~~~

However if the character is not on Windows 1252, bad things:

~~~
$ cp alfa.m4a ⌂.m4a
$ tageditor/tageditor -gf ⌂.m4a
Error: An IO failure occured when reading the file "�.m4a".
~~~

I would guess that you are using Windows ANSI functions somewhere instead of
the Unicode variant:

http://cygwin.com/ml/cygwin/2017-07/msg00441.html

[1]://wikipedia.org/wiki/Windows-1252

**Comment by svnpenn** [comment] 2017-08-20 18:40
@Martchus I did a bisect and came up with this:

~~~
77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43 is the first bad commit
commit 77da65ddf79bbcbe8b5f2f16d8125d4bf9e99d43
Author: Martchus <martchus@gmx.net>
Date:   Sun Dec 18 17:23:45 2016 +0100

    Convert args to UTF-8 under Windows
~~~

So it appears 77da65d is the culprit

**Comment by Martchus** [comment] 2017-08-20 21:05
> I would guess that you are using Windows ANSI functions somewhere instead of
the Unicode variant.

Me, too and that would be the case if the `USE_NATIVE_FILE_BUFFER` is not enabled in your case (maybe due to some bug in the build script).

So is https://github.com/Martchus/cpp-utilities/blob/master/io/nativefilestream.cpp#L33 executed (3rd time I ask this question)?

If not, how is the compiler line of `basicfileinfo.o`? It should contain `-DCPP_UTILITIES_USE_NATIVE_FILE_BUFFER` eg.
```
/usr/lib/ccache/bin/clang++  -DCPP_UTILITIES_USE_NATIVE_FILE_BUFFER -DDEBUG_BUILD -DLEGACY_API -DLOGGING_ENABLED -Dtagparser_EXPORTS -Wall -Werror -g -fPIC   -fprofile-instr-generate -fcoverage-mapping -std=gnu++14 -o CMakeFiles/tagparser.dir/basicfileinfo.cpp.o -c /run/media/martchus/files/programming/projects/c++/cmake/tagparser/basicfileinfo.cpp
```
(You can get this specific line by invoking `make -B VERBOSE=1 basicfileinfo.o`)

If not, does `/your/install/prefix/share/c++utilities/cmake/c++utilitiesStaticTargets.cmake` (or the shared variant if you don't link against c++utilities statically) contain the variable? It should look like:
```
set_target_properties(c++utilities_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CPP_UTILITIES_USE_NATIVE_FILE_BUFFER;CPP_UTILITIES_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "/run/media/devel/build/qtcreator/tageditor-Desktop-x86_64-w64-mingw32-Release/install/include"
  INTERFACE_LINK_LIBRARIES "/usr/x86_64-w64-mingw32/lib/libiconv.a"
)
```

Interesting that reverting 77da65d helps. When reverting it, the arguments (including the file path) are not converted to Unicode. Maybe this "harmonizes better" with using the Windows ANSI function. But as you mentioned yourself, the use of the ANSI function is the actual problem.

BTW:
* The code for avoiding the ANSI function is in: c++utilities/io/nativefilestream.cpp
* That's the executable I've tested and which works for me: https://martchus.no-ip.biz/repo/win/static/devel/tageditor-devel-2.2.5-319.3525588-static-x86_64-w64-mingw32.tar.xz

**Comment by svnpenn** [comment] 2017-08-20 22:05
> So is
> https://github.com/Martchus/cpp-utilities/blob/master/io/nativefilestream.cpp#L33
> executed (3rd time I ask this question)?

Yeah, you keep asking it, but you have yet to say how I would actually check
that. Remember carefully, I did not write this code, you did.

> If not, how is the compiler line of basicfileinfo.o? It should contain
> -DCPP_UTILITIES_USE_NATIVE_FILE_BUFFER eg.

Here is the line from my build:

~~~
/usr/bin/x86_64-w64-mingw32-g++.exe -DCPP_UTILITIES_STATIC -DLEGACY_API
-DTAG_PARSER_STATIC -I/var/cache/glade/tagparser/.. -I/var/cache/glade/tagparser
-isystem /usr/x86_64-w64-mingw32/sys-root/mingw/include -std=gnu++14 -o
CMakeFiles/tagparser_static.dir/basicfileinfo.cpp.o -c
/var/cache/glade/tagparser/basicfileinfo.cpp
~~~

> If not, does
> /your/install/prefix/share/c++utilities/cmake/c++utilitiesStaticTargets.cmake
> (or the shared variant if you don't link against c++utilities statically)
> contain the variable? It should look like:

No, it doesnt. At this point I realized the issue. I was using
`-DUSE_NATIVE_FILE_BUFFER=1` with TagEditor rather than CPP-Utilities. Changing
this fixes the issue. I see you have this documented too, so my bad:

http://github.com/Martchus/cpp-utilities/blob/master/doc/buildvariables.md#windows-specific

**Comment by Martchus** [comment] 2017-08-20 23:43
Yes, it is documented. However, the documentation doesn't clearly state at which level the native file buffer is implemented. I fixed that and also added notes in the README of tagparser and tag editor so the change someone reads it will be higher.

In the next major release of c++utilities this option will be the default anyways. I just don't change it yet because it affects the ABI.

Independently who wrote the code, there are various ways to check whether a line is executed:
* adding some debug output (preferably only ASCII characters)
* using the debugger
* code coverage analysis

I didn't want to state the obvious.

I'm closing since it is fixed.

**Closed by Martchus** 2017-08-20 23:43 UTC
Labels: bug, Windows-only
