### ISSUE TITLE
Window explorer doesn't show embedded cover in thumbnails.

### ISSUE THREAD

**Issue by brachna** [Martchus/tageditor#8] opened 2016-11-13 03:06 UTC
Windows 8.1 x64
"tageditor-devel-3-static-x86_64-w64-mingw32.tar.xz"

Sample file:
[HOLY FAWN - Reykur (Single) - 01 Reykur (Single)-old.zip](https://github.com/Martchus/tageditor/files/587567/HOLY.FAWN.-.Reykur.Single.-.01.Reykur.Single.-old.zip)

Got it by converting FLAC with embedded image (made in Tag Editor actually) using bat command:
ffmpeg -i %1 -c:a libmp3lame -b:a 320k -id3v2_version 3 "%~n1.mp3"
Resulting mp3 shows embedded cover in thumbnail view (big icons for example).
When resaved with Tag Editor it stops showing cover.

**Comment by brachna** [comment] 2016-11-14 01:22
After a OS reboot (maybe ccleaner does something too) icon shows up. I think this should be closed.
Can you reproduce?

**Comment by Martchus** [comment] 2016-11-14 09:12
I haven't looked into it yet.

**Comment by Martchus** [comment] 2016-11-19 13:58
I can't reproduce so I'll close this.

**Closed by Martchus** 2016-11-19 13:58 UTC
Labels: bug
