### ISSUE TITLE
Throws error on file with unicode characters in filename

### ISSUE THREAD

**Issue by brachna** [Martchus/tageditor#4] opened 2016-11-12 13:20 UTC
Windows 8.1 x64.
"tageditor-devel-2-static-x86_64-w64-mingw32.tar.xz"

Nice application, but there's a problem when trying to edit an mp3 file with unicode characters in filename (for example, Glóandi.mp3).
I get "The file could not be opened because an IO error occured."

**Comment by Martchus** [comment] 2016-11-12 14:06
I can not reproduce this under Windows 10. German umlauts and also your example work for me.

**Comment by brachna** [comment] 2016-11-12 14:22
On my machibe it happens when using GUI at least. Were there fixes regarding this after "tageditor-devel-2-static-x86_64-w64-mingw32.tar.xz" was released?

**Comment by Martchus** [comment] 2016-11-12 14:38
I did this build a few days ago - so no. It is more likely a newly introduced regression. However, I can not reproduce (and I'm using the same build as it is the latest I have for Windows).

**Comment by Martchus** [comment] 2016-11-19 14:00
Not sure what to do about it since I can't reproduce. Is only the GUI affected?

**Comment by brachna** [comment] 2016-11-19 18:51
No, not only GUI. Very confusing error, it seems like Windows changes input unicode characters on the fly when they're typed in commandline.

If I copy-paste "05 - Glóandi.mp3" into commandline - it changes into "05 - Gloandi.mp3".

Even using Python 3.
`filename = "05 - Glóandi.mp3"`
`subprocess.call( ["tageditor.exe", "get", "artist", "--files", filename] )`
I get
`Error: An IO failure occured when reading the file "05 - Gloandi.mp3".`

**Comment by brachna** [comment] 2016-11-30 12:42
Here's a video of what happens on my system.
[2016-11-30 15-34-07.zip](https://github.com/Martchus/tageditor/files/621791/2016-11-30.15-34-07.zip)

**Comment by Martchus** [comment] 2016-11-30 14:54
Ok, I'll look into it again.

But what is the character set you're actually using? I'm not sure what Python 3 and its subprocess module actually use or what your terminal actually use.

Since the GUI is also affected, I assume that the character set returned by http://doc.qt.io/qt-5/qtextcodec.html#codecForLocale is not what std::fstream expects.

**Comment by brachna** [comment] 2016-11-30 15:36
By default active codepage is 866.
I tried setting commandline to supposed unicode codepage 65001, but that didn't help.

Python 3 test was just used to entrust Python with correct unicode decoding. I'm not sure it had any effect here.

**Comment by Martchus** [comment] 2016-11-30 20:38
The problem is the `std::fstream::open` function. Not sure which character set is expected under the different platforms. For me UTF-8 works under GNU/Linux and Latin1 works under Windows. Because I wasn't sure I just let Qt do the decision which doesn't seem to work in your case.

The following build forces Latin1: [tageditor-force-latin1.zip](https://github.com/Martchus/tageditor/files/622908/tageditor-force-latin1.zip)
Does this work for you?

This build forces UTF-8 and doesn't work for me: [tageditor.zip](https://github.com/Martchus/tageditor/files/622905/tageditor.zip)

**Comment by brachna** [comment] 2016-12-01 00:54
Unfortunately both builds didn't work, but behavior changed.
Before, as shown in the video, if I select "Glóandi.mp3" TagEditor for some reason would look for "Gloandi.mp3", now it doesn't.

**Comment by Martchus** [comment] 2016-12-01 08:56
Really? In the video the GUI error message shows `Glóandi`. But so far I don't know which character set is required in your case and why Qt doesn't pick the right one. I don't know much about Windows, but maybe you can change the character set somewhere (as I said, in my setup Latin1 works fine).

BTW: The CLI always assumes the specified arguments are UTF-8 so this might be another problem in Windows, too.

**Comment by brachna** [comment] 2016-12-01 10:08
In the video the error message shows "Glóandi" file, but if I copy-paste it and rename it into "Gloandi" and then choose "Glóandi" file - the error will not show up. That's because it will choose "Gloandi" file and not "Glóandi" one. It's really weird.
Unicode support on Windows was always crap. I'm surprised to read you don't have problems on Windows 10. Looks like they can fix things sometimes.

Btw, even though the error shows "Glóandi", isn't it still uses unicode value inside QString by that point?

**Comment by Martchus** [comment] 2016-12-01 10:22
Last time I tested only with WINE where it worked with Latin1 (and not with UTF-8). But yes, it also works under Windows 10 for me (only regular release build tested). I guess it depends on your locale settings.

To your last question: Yes

And in the CLI I just pass the string as it is provided to `std::fstream::open` and log. But maybe Windows messes the argument when passing it to the application.

**Comment by brachna** [comment] 2016-12-01 11:37
> But maybe Windows messes the argument when passing it to the application.

It sure is, I can't explain behavior I mentioned above otherwise.
I assume using Qt classes instead of standard library to deal with file operations is not an option?
If not it's ok, but I'm just out of ideas. Long ago I made a little app that could load files with unicode filenames on my machine, but that one was using MSVC.

**Comment by Martchus** [comment] 2016-12-01 13:11
> I assume using Qt classes instead of standard library to deal with file operations is not an option?

No - the underlying tagparser library should not depend on Qt and switching to another file IO implementation would be a lot of work.

I've read that MSVC provides an overload for `std::fstream::open` which takes UTF-16, but I use mingw-w64 for this project.

Under mingw-w64 I might be able to use `__gnu_cxx::stdio_filebuf b (_wopen (L"filename", _O_RDONLY));`. I'll test later.

Not sure about the CLI. If Windows really messes the arguments I'm afraid I can not do anything. Does setting fields values with non-ASCII characters via CLI work for you? Since the Tag Editor always assumes provided values are UTF-8 this likely doesn't work, too.

**Comment by brachna** [comment] 2016-12-02 03:55
Now that you mentioned it, indeed, setting fileds via CLI doesn't work. But not only non-ASCII characters don't work, but ASCII ones don't work either.
`tageditor set artist="11" --files test.mp3`
That sets artist field to "ㄱ"

**Comment by Martchus** [comment] 2016-12-09 07:49
Fixing encoding issues might be difficult and will take some time, see https://github.com/Martchus/tageditor/issues/15.

**Comment by brachna** [comment] 2016-12-09 16:49
I understand.

**Comment by Martchus** [comment] 2016-12-18 21:28
Does the following work for you? https://github.com/Martchus/tageditor/files/659614/tageditor.zip

See https://github.com/Martchus/tageditor/issues/15 (both issues are actually very related)

**Comment by brachna** [comment] 2016-12-18 23:42
GUI version works now! Setting tags also works with both ASCII and unicode characters.

With both native Russian locale and 65001 active code page I get wrong result if I use tageditor from command line though.
`tageditor set artist="777" --files "test.mp3"`
artist tag is set to "㜷"

**Comment by Martchus** [comment] 2016-12-27 23:22
The last issue should be fixed with https://github.com/Martchus/tagparser/commit/369a241131e4b352c444c899217855656427bf53 now.

**Comment by brachna** [comment] 2016-12-28 17:21
Is new build available so I can try?

**Comment by Martchus** [comment] 2016-12-28 17:24
Not yet, I'll make a new build later.

**Comment by Martchus** [comment] 2016-12-29 00:36
New devel build including latest changes: https://martchus.no-ip.biz/repo/win/static/tageditor-devel-7-static-x86_64-w64-mingw32.tar.xz

**Comment by brachna** [comment] 2016-12-30 22:58
Thanks.
With provided build TagEditor now correctly sets both ASCII and Unicode characters in GUI mode.
In console mode it correctly sets ASCII characters as well now. Unicode characters like "百" crash the program though.
Anyway original issue was about GUI mode, should this issue be closed and further discussion moved to #15?

Happy new year!

**Comment by Martchus** [comment] 2016-12-30 23:18
Nice, so the initially reported issue is fixed. It makes sense to close this an do further discussion in #15.

**Closed by Martchus** 2016-12-30 23:18 UTC
Labels: bug, Windows-only

**Comment by svnpenn** [comment] 2017-08-17 02:33
https://github.com/Martchus/tageditor/issues/21

**Comment by svnpenn** [comment] 2017-08-17 02:34
https://github.com/stedolan/jq/issues/811
