### ISSUE TITLE
Broken encoding when setting tags on certain ID3v2 combinations

### ISSUE THREAD

**Issue by poelzi** [Martchus/tageditor#19] opened 2017-05-17 15:51 UTC
I'm using the command line options to set id3 tags on mp3:

> ~/src/tageditor/tageditor -s  --encoding=utf8 -v 'artist=Very good artist' -f *.mp3

If no id3v2 version is specified and I set the desired encoding to utf8 and the file is of version id3v2.3 for example, then the tag in written with broken encoding.
It is flagged as UTF16 in the tag, but the value is never converted from UTF-8 which will break some tools, but not all.
Problematic part is in mainfeatures.cpp:
```
                                        TagTextEncoding usedEncoding = denotedEncoding;
                                        cerr << "denoted encoding: " <<  textEncodingToCodecName(denotedEncoding) << endl;
                                        if(!tag->canEncodingBeUsed(denotedEncoding)) {
                                            usedEncoding = tag->proposedTextEncoding();
                                        }
                                        
                                        cerr << "used encoding: " <<  textEncodingToCodecName(usedEncoding) << endl;
                                        convertedValues.emplace_back(relevantDenotedValue->value, TagTextEncoding::Utf8, usedEncoding);
```
I added some debugging output.
usedEncoding gets set to UTF16 when I don't specify a id3v2 version and it's 3 for example.

Workaround:
Setting `--id3v2-version=4`.

**Comment by Martchus** [comment] 2017-05-17 15:57
Ok, so the conversion of the value from UTF-8 to UTF-16 does not happen. I'll try to fix and reproduce later. Thanks for the feedback.

**Comment by Martchus** [comment] 2017-05-18 18:21
I extended the documentation of the `--encoding` option (https://github.com/Martchus/tageditor/commit/d052db8abbf86d01b1b39ef5663a8e24648ef30c). You'll also get now a warning when the specified encoding is not supported by the format/version (https://github.com/Martchus/tageditor/commit/cbe6b800cde647096b6f4ff305a6bbfc46e063fc).

> If no id3v2 version is specified and I set the desired encoding to utf8 and the file is of version id3v2.3 for example, then the tag in written with broken encoding.
> It is flagged as UTF16 in the tag, but the value is never converted from UTF-8 which will break some tools, but not all.

I couldn't reproduce this. At least with a test file from mkvtoolnix testsuite (which has ID3v2.3 tags) the value is converted to UTF-16. However, I've noticed that the BOM is missing when using the CLI. This should be fixed with (https://github.com/Martchus/tagparser/commit/23e84886d490fc347129a820a462c4eefb4fad46). I also added a test for correct encoding and BOM (https://github.com/Martchus/tageditor/commit/71a4c48f991aa4939d8ad0c953bc50792063283b).

**Closed** 2018-06-21 08:15 UTC
Labels: bug, not reproducible
