### ISSUE TITLE
Large files (over 6GB) breaks

### ISSUE THREAD

**Issue by zaonpt** [Martchus/tageditor#61] opened 2021-01-21 20:17 UTC
When writing vids over 3gb (tested on 6GB) it breaks.
The percentage progress seems to be wrong from the beginning when it reaches 100% it only wrote 3GB ...around that.
Tested on Windows 10. And several vids. If below 3gb It all works well, but over that it stops on 3GB.

**Comment by Martchus** [comment] 2021-01-21 20:41
What is the format? That can make a very important difference. At least some output from media info would be useful. And what was the tool you've been using to create one of those files? (Generally it would be nice to have a sample file but I suppose due to the size this is not possible.)

About the percentage: The percentage usually only relates to the current internal phase when writing a file and not the entire process so it is not that helpful in general and might be misleading.

**Comment by Martchus** [comment] 2021-01-21 20:46
And what settings have you been using (padding, tag/index position)? And what was the padding and tag/index position before? Is it rewriting the file (so a backup file is created)?

**Comment by zaonpt** [comment] 2021-01-22 10:30
All defaults

A quinta, 21/01/2021, 20:46, Martchus <notifications@github.com> escreveu:

**Comment by zaonpt** [comment] 2021-01-22 10:30
Yes backup is created. He rewrites the file untill gets to 3GB

A quinta, 21/01/2021, 20:46, Martchus <notifications@github.com> escreveu:

**Comment by Martchus** [comment] 2021-01-22 10:44
Did you read my first comment?

**Comment by zaonpt** [comment] 2021-01-22 11:22
[image: Captura de ecrã 2021-01-22 112044.png]

**Comment by zaonpt** [comment] 2021-01-22 12:16
Do you have any suggestions to change settings to allows this large files
to be saved?

**Comment by Martchus** [comment] 2021-01-22 12:29
> [image: Captura de ecrã 2021-01-22 112044.png]

Looks like you've tried to send an image but it didn't work.

> Do you have any suggestions to change settings to allows this large files
> to be saved?

You could come up with a PR for the tagparser repository to fix the bug which lies somewhere within the code.

**Comment by zaonpt** [comment] 2021-01-22 12:31
> Did you read my first comment?
weird I didn't get the email for that comment. I was replying from Gmail. sorry.
I will gather more info and post here.

**Comment by zaonpt** [comment] 2021-01-22 12:32
> Did you read my first comment?

Wierd, i didnt get the email for that post. I've beem replying from gmail.
I will gather more info and post it

**Comment by zaonpt** [comment] 2021-01-22 12:39
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
resolution: 4320x2160
fps: 60
audio: Codec: MPEG AAC Audio (mp4a)
file size 7.63 GB

I have other vids with the same codec and I did change the thumb of those vids with your software. I Did a lot of them and in all of them, the pattern was the same vids over 3GB do not work everything below it does.

**Comment by Martchus** [comment] 2021-01-25 20:24
So I assume the container format is MP4. Unfortunately I can not reproduce the problem. It works just fine with a > 6 GiB MP4 file using the `co64` atom (produced by ffmpeg).

I've also tested a Matroska file just in case that was the container you were using. The performance is admittedly very bad for Matroska and when dealing with big files that's really problematic. However, it nevertheless seems to work.

This might still be a valid bug request. Even if your file is damaged this should be handled gracefully and never lead to this behavior. However, without a file to reproduce there's nothing I can do. It would possibly help if you would send me the "HTML info" of your file, though. This is an HTML document containing technical information about your file such as the element structure which can be generated by the tag editor's CLI via `tageditor html-info --file path/to/your/file.mp4 --output-file info.html`.

**Comment by zaonpt** [comment] 2021-01-26 11:06
Sorry for not providing enough info. I hope your tool get even better. For
now i found a flawless altgernative. TY. You can close this "bug report". GL

**Comment by Martchus** [comment] 2021-01-26 11:59
I'm closing this because the mere fact that the file was big does not seem significant. However, there's still a bug somewhere in my code and it would still be great to find it.

**Closed by Martchus** 2021-01-26 11:59 UTC
Labels: bug
